### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jonycelio** [jbranchaud/atom-search#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Search](https://github.com/jbranchaud/atom-search) package, v0.4.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jonyw4/.atom/packages/Search/lib/search.coffee:52

TypeError: undefined is not a function
  at Object.module.exports.getSearchTerm (/Users/jonyw4/.atom/packages/Search/lib/search.coffee:52:25)
  at Object.module.exports.getSearchUrl (/Users/jonyw4/.atom/packages/Search/lib/search.coffee:55:19)
  at atom-workspace.<anonymous> (/Users/jonyw4/.atom/packages/Search/lib/search.coffee:20:13)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -0:00.0 search:google (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "feedback"
    ],
    "themes": [
      "isotope-ui",
      "behave-theme"
    ],
    "projectHome": "Applications/XAMPP/xamppfiles/htdocs"
  }
}
```

### Installed Packages

```coffee
# User
Search, v0.4.0
atom-spotify, v0.6.1
auto-update-packages, v0.2.2
autocomplete-plus, v1.1.0
behave-theme, v1.2.0
editor-stats, v0.16.0
file-icons, v1.4.8
isotope-ui, v1.2.1
linter, v0.10.0
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-scss-lint, v0.0.11
minimap, v3.5.6
notifications, v0.25.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by jbranchaud** [comment]
@jonycelio Thanks. I'll look into this.
