### ISSUE TITLE
Cannot read property 'command' of undefined

### ISSUE THREAD

**Issue by HerbCSO** [jbranchaud/atom-search#14]
Happens immediately at startup.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [search](https://github.com/jbranchaud/atom-search) package, v0.5.0
### Stack Trace

Failed to activate the search package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/carsten.dreesbach/.atom/packages/search/lib/search.coffee:8:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "._*",
      ".DS_Store",
      "Thumbs.db",
      "target"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
achievements, v0.7.2
atom-pair, v1.1.6
auto-update-packages, v1.0.0
color-picker, v2.0.7
command-logger, v0.23.0
editor-stats, v0.17.0
emmet, v2.3.10
file-icons, v1.5.8
language-applescript, v0.2.0
linter, v1.0.4
linter-javac, v0.1.4
linter-rubocop, v0.2.7
minimap, v4.10.0
search, v0.5.0
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by dwillitzer** [comment]
+1 Same issue.

**Comment by Lujaw** [comment]
+1 same here after the update to atom 1
