### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by georgeyord** [jbranchaud/atom-search#15]
> apm install search

```
Installing search to /home/user/.atom/packages 
TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom/resources/app/apm/lib/install.js:341:28
    at Request._callback (/usr/share/atom/resources/app/apm/lib/request.js:59:22)
    at Request.self.callback (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

> lsb_release -a

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:    14.10
Codename:   utopic
```

**Comment by wesinator** [comment]
this is because of https://github.com/atom/atom.io/issues/191 
fixed by #17 

#16, #10
