### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by kyleridolfo** [jbranchaud/atom-search#16]
```
Installing “search@0.5.0” failed.Hide output…


TypeError: Cannot read property 'latest' of undefined
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:285:28
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/apm/lib/request.js:59:22)
    at Request.self.callback (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:1057:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:1003:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by wesinator** [comment]
yep, this is because of https://github.com/atom/atom.io/issues/191
